DISH_TYPE_NAME = {
    'CƠM VĂN PHÒNG': 'Món ăn',
    'ĐỒ UỐNG': 'Đồ uống',
    'CƠM RANG (BÁN BUỔI TRƯA)': 'Món ăn',
    'PHỞ': 'Món ăn',
    'MÓN CHÍNH': 'Món ăn',
    'Nước Ép Và Đồ Uống': 'Đồ uống',
    'CƠM GÀ': 'Món ăn',
    'Cà Phê': 'Đồ uống',
    'Món mới ĐẶC BIỆT': 'Đồ uống',
    'SỮA CHUA HOA QUẢ': 'Đồ uống',
    'NƯỚC ÉP': 'Đồ uống',
    'MENU CƠM': 'Món ăn',
    'MÌ TRỘN': 'Món ăn',
    '❤ Quán 26❤': 'Món ăn',
    'Bánh mỳ kẹp': 'Món ăn',
    'Bánh mỳ chảo': 'Món ăn',
    'Nước giải khát': 'Đồ uống',
    'Xôi thập cẩm': 'Món ăn',
}
